name: spider_words
description: "Learn English by interacting and linking between types of terms and questions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path: ^1.9.0
  path_provider: ^2.1.1
  provider: ^6.1.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_markdown: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.ico"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/nouns.db
    - assets/icon.ico
    - assets/sounds/wrong.mp3
    - assets/sounds/correct.mp3
  uses-material-design: true